version: "3.8"
services:
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - ${PORT}:${PORT}
    networks:
      - pern-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/data/db
    networks:
      - pern-app
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  app:
    image: react-app-dev
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - pern-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules

networks:
  pern-app:
    driver: bridge

volumes:
  data: {}
